# Eager Mode

In [20]:
import tensorflow as tf
import numpy as np

Everything is eager by default in tensorflow 2.0

In [21]:
a = np.array([1., 2.])
b = np.array([2., 5.])

tf.add(a, b)

<tf.Tensor: id=53, shape=(2,), dtype=float64, numpy=array([3., 7.])>

## Graph Model : AutoGraph
As tensorflow suggest (https://www.youtube.com/watch?v=jh4ITuOytE4), we can use Autograph to automatically convert the eager mode into graph mode by using the tf.function decorator

The following code fist compiles the code inside the add function into graph code before to execute it. Note that if you remove the @tf.function decorator the code will work perfectly but will not be executed in graph mode.

In [26]:
@tf.function
def add_fc(a, b):
    return tf.add(a, b)

print (add_fc(a, b))

tf.Tensor([3. 7.], shape=(2,), dtype=float64)


The following code show the code generated to create the graph

In [24]:
def add_fc(a, b):
    return tf.add(a, b)

print(tf.autograph.to_code(add_fc))

from __future__ import print_function

def tf__add_fc(a, b):
  try:
    with ag__.function_scope('add_fc'):
      do_return = False
      retval_ = None
      do_return = True
      retval_ = ag__.converted_call('add', tf, ag__.ConversionOptions(recursive=True, verbose=0, strip_decorators=(ag__.convert, ag__.do_not_convert, ag__.converted_call), force_conversion=False, optional_features=ag__.Feature.ALL, internal_convert_user_code=True), (a, b), {})
      return retval_
  except:
    ag__.rewrite_graph_construction_error(ag_source_map__)



tf__add_fc.autograph_info__ = {}



# Graph mode and eager mode  with a keras model

In [34]:
# Flatten
model = tf.keras.models.Sequential()
# Add layers
model.add(tf.keras.layers.Dense(256, activation="relu"))
model.add(tf.keras.layers.Dense(128, activation="relu"))
model.add(tf.keras.layers.Dense(10, activation="softmax"))

By calling model.predict you get a numpy array but the output is not differentiable

In [38]:
model_output = model.predict(np.zeros((1, 30)))
model_output

array([[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]], dtype=float32)

By calling model(), eager execution is used and the output is differentiable

In [40]:
model_output = model(np.zeros((1, 30)))
model_output

<tf.Tensor: id=683, shape=(1, 10), dtype=float32, numpy=array([[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]], dtype=float32)>

But you execute the model in graph mode by using the @tf.function decorator

In [43]:
@tf.function
def predict(x):
    model(x)

model_output = predict(np.zeros((1, 30)))
model_output

In [46]:
model.predict(np.zeros((1, 30)))

array([[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]], dtype=float32)